#!/usr/bin/env bash

for file in test/*.js; do
  if [[ "$file" != "test/testValidator.js" && "$file" != "test/remotes.js" ]]; then
    echo
    echo "$file" | sed 's/test\///' | sed 's/\.js//'
    mocha "$file" | egrep -s '\d passing|\d failing'
  fi
done
